### ISSUE TITLE
Add 20.8.12.2 Altinity Stable Release Update

### ISSUE THREAD

**Issue by alex-zaitsev** [johnhummelAltinity/betadocumentationissues#2]
Please add 20.8.12.2 Release Update

Release notes:
* Fixed a rare bug that might result in corrupted data when merging from wide to compact parts. 

We recommend upgrading to this release all 20.8 users who are using compact parts.

**Comment by johnhummelAltinity** [comment]
@alex-zaitsev Added and updated to both the Beta and the Production sites.
